spring.application.name=demo
telegram.bot.token=8403848389:AAE58qZ9LcfBVVa_gtMz5V0hHHgwjNUV1pY
telegram.bot.username=vzletaudit_bot
openai.api.key=${OPENAI_API_KEY}
bitrix24.webhook=https://???-??????.bitrix24.ru/rest/1/???_??????/
telegram.chat.url=https://t.me/vzlet_agency
serpapi.key=???_????_??_serpapi
socks.proxy.host=127.0.0.1
socks.proxy.port=10808
telegram.bot.connection.timeout=60
